### ISSUE TITLE
Type cast needed when using result of DateTime::format()

### ISSUE THREAD

**Issue by holtkamp** [DateAndTime4PHP/DateTime#1]
Pretty sure a typecast to integer `(int)` is needed here:

https://github.com/DateAndTime4PHP/DateTime/blob/c6b4def3794adfced5dece3da044b63c9d730cb8/src/Date.php#L81-L94

Since [`DateTime::format()`](http://php.net/manual/en/datetime.format.php) returns a `string`

**Comment by holtkamp** [comment]
Nice library, will have a look soon!

**Comment by heiglandreas** [comment]
Fixed with commit 09e0381b4a936a4058ee8e1977ad093564c56f29

Thanks for raising awareness ;-)
